name: integrate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

configure: &default
  env:
    REPORT_EXIT_STATUS: yes 
    NO_INTERACTION: yes
    GITHUB: "yes"
    TEST_PHP_ARGS : "--show-diff"
    enable_session: "yes"
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install
      run: |
        sudo apt-get install -y \
          php-cli \
          php-pear \
          libcurl-ocaml-dev \
          re2c
    - name: Prepare
      run: |
          phpize
    - name: Build
      run: |
          ./configure
    - name: Make
      run: |
          make
    - name: Test
      run: |
          make test

jobs:
  php-70-NTS:
    name: "PHP-7.0"
    env:
      PHP: "7.0"
      enable_debug: "yes"
      enable_maintainer_zts: "no"
    <<: *default
  php-71-NTS:
    name: "PHP-7.1"
    env:
      PHP: "7.1"
      enable_debug: "yes"
      enable_maintainer_zts: "no"
      enable_session: "yes"
    <<: *default
